update gitignore

diff --git a/Kolloid/kolloid b/Kolloid/kolloid
--- a/Kolloid/kolloid
+++ b/Kolloid/kolloid
@@ -3,22 +3,52 @@
 # @Copyright:       @2026 by Johannes a.d.F. K r ä m e r
 
 programmName="Kolloid Station";
-programmVersion="1.7";
+programmVersion="1.9";
 heizplatteRelais=7;
 trafoRelais=13;
 scriptPath=$(cd $(dirname "$0"); pwd);
 libsPath="$scriptPath/libs";
 soundPath="$scriptPath/sounds";
-trap ctrl_c INT;  # CTRL + C abfangen & Relais ausschalten #### FUNKTIONIERT NICHT IMMER ??!?!?!
-function ctrl_c() {
-    230V $heizplatteRelais 0 1;
-    230V $trafoRelais 0 1;
-    printf "\n\e[1;31m > !BYEBYE!\e[0m \n\n";
-    exit 1;
+# Linux lockfile
+LOCKFILE="/tmp/kolloid.lock"
+exec 200>"$LOCKFILE"
+flock -n 200 || {
+    printf "\n\e[1;31m > Kolloid läuft bereits!\e[0m\n\n"
+    exit 1
 }
-230V $heizplatteRelais 0 1;
-230V $trafoRelais 0 1;
-kolloidElementsArray=(au ag pt pd ir);
+
+# Array für PID's
+bgPids=()
+trap '' TSTP; # CTRL+Z verhindern
+# ---------------------------------------
+# Cleanup
+# ---------------------------------------
+shutdownRelays() {
+    # Traps deaktivieren (keine Schleife)
+    trap - INT EXIT TERM ERR HUP
+    printf "\n\e[0m | > Cleanup läuft...\e[0m"
+    # Alle gestarteten Hintergrundprozesse beenden
+    for pid in "${bgPids[@]}"; do
+        printf "\n \e[0m|\e[1;31m > Kill ProcessID: $pid \e[0m"
+        kill "$pid" 2>/dev/null
+    done
+    # Relais sicher ausschalten
+    230V $heizplatteRelais 0 1 >/dev/null 2>&1
+    230V $trafoRelais 0 1 >/dev/null 2>&1
+    printf "\n \e[0m| > !BYEBYE!\e[0m\n\n"
+    exit 0
+}
+# ---------------------------------------
+# Traps registrieren
+# ---------------------------------------
+trap shutdownRelays INT EXIT TERM HUP
+set -E
+
+
+230V $heizplatteRelais 0 1 >/dev/null 2>&1
+230V $trafoRelais 0 1 >/dev/null 2>&1
+
+kolloidElementsArray=(au ag pt pd);
 kolloidWaterSizeArray=(100 200 400 1000 2000);
 source "$libsPath/pattern.sh" || exit 1; 
 source "$libsPath/getENV.sh" || exit 1; 
@@ -33,41 +63,35 @@ showLogo;
 if (( ${size} == 100 )); then
     _endPlatte=480; # geprüft: 480 ok
     if [ $metal == "au" ]; then
-        maxRuntime=900; # 15 Minuten
+        maxRuntime=420; #420 7 Minutens
     elif [ $metal == "ag" ]; then
         maxRuntime=300; # 5 Minuten
     elif [ $metal == "pt" ]; then
-        maxRuntime=900; # 15 minuten
+        maxRuntime=420; # 7 minuten
     elif [ $metal == "pd" ]; then
-        maxRuntime=1200; # 20 minuten 
-    elif [ $metal == "ir" ]; then
-        maxRuntime=1200; # 20 minuten
+        maxRuntime=420; # 7 minuten 
     fi
 elif (( ${size} == 200 )); then
     _endPlatte=550; # geprüft: 550 ok
     if [ $metal == "au" ]; then
-        maxRuntime=900; # 15 minuten
+        maxRuntime=600; # 10 minuten
     elif [ $metal == "ag" ]; then
         maxRuntime=420; # 7 minuten
     elif [ $metal == "pt" ]; then
         maxRuntime=900; # 15 minuten
     elif [ $metal == "pd" ]; then
         maxRuntime=1200; # 20 minuten
-    elif [ $metal == "ir" ]; then
-        maxRuntime=1200; # 20 minuten
     fi
 elif (( ${size} == 400 )); then
-    _endPlatte=950; # nicht geprüft: ##################
+    _endPlatte=720; # nicht geprüft: ######################################################################
     if [ $metal == "au" ]; then
-        maxRuntime=720; # 15 minuten nachjustiert, prüfen
+        maxRuntime=720; # 12 minuten
     elif [ $metal == "ag" ]; then
         maxRuntime=420; # 7 minuten ###################
     elif [ $metal == "pt" ]; then
         maxRuntime=900; # 15 minuten ##################
     elif [ $metal == "pd" ]; then
         maxRuntime=1200; # 20 minuten #################
-    elif [ $metal == "ir" ]; then
-        maxRuntime=1200; # 20 minuten ###############
     fi
 elif (( ${size} == 1000 )); then
     _endPlatte=2070; # geprüft: 2070 ok
@@ -79,8 +103,6 @@ elif (( ${size} == 1000 )); then
         maxRuntime=1800; # 30 minuten
     elif [ $metal == "pd" ]; then
         maxRuntime=1800; # 30 minuten
-    elif [ $metal == "ir" ]; then
-        maxRuntime=1800; # 30 minuten
     fi
 elif (( ${size} == 2000 )); then
     _endPlatte=5400;  # geprüft:  5400 ok
@@ -91,8 +113,6 @@ elif (( ${size} == 2000 )); then
     elif [ $metal == "pt" ]; then
         maxRuntime=3600; # 60 minuten
     elif [ $metal == "pd" ]; then
-        maxRuntime=3600; # 60 minuten
-    elif [ $metal == "ir" ]; then
         maxRuntime=3600; # 60 minuten
     fi
 fi
@@ -112,18 +132,16 @@ elif [ $metal == "ag" ]; then
         time=$(((($size/10) * 2) * $ppm));
     fi
 elif [ $metal == "pt" ]; then
-    time=$(((($size/2) * 23) * $ppm)); # #################################### ZEIT ERMITTELN !!!!! 
+    time=$(((($size/2) * 11) * $ppm)); # #################################### ZEIT ERMITTELN !!!!! 
 elif [ $metal == "pd" ]; then
-    time=$(((($size/2) * 18) * $ppm)); # #################################### ZEIT ERMITTELN 
-elif [ $metal == "ir" ]; then
-    time=$(((($size/4) * 10) * $ppm)); # #################################### ZEIT ERMITTELN !!!!!!
+    time=$(((($size/2) * 12) * $ppm)); # #################################### ZEIT ERMITTELN 
 fi
 
-echo -e " .------------------------------------------------------------------------------.";
-echo -e " | Material\\tMenge (ml)\\tPPM\\t\\tKochzeit\\tPlasmazeit\\t|";
-echo -e " |------------------------------------------------------------------------------.";
-echo -e " | ${metal}\\t\\t${size} ml\\t\\t${ppm} PPM\\t\\t$(date -d@$(($_endPlatte)) -u +%H:%M:%S)\\t $(date -d@$(( $time)) -u +%H:%M:%S)\\t|";
-echo -e " *------------------------------------------------------------------------------*\n";
+echo -e " .-----------------------------------------------.";
+echo -e " | E\\tml\\tPPM\\tKochen\\t\\t Plasma  |";
+echo -e " |-----------------------------------------------.";
+echo -e " | ${metal}\\t${size} ml\\t${ppm} PPM\\t$(date -d@$(($_endPlatte)) -u +%H:%M:%S)\\t $(date -d@$(( $time)) -u +%H:%M:%S)|";
+echo -e " *-----------------------------------------------*\n";
 if [ $metal == "au" ]; then
     printf "\n > 1) Elektroden (${metal}) einspannen & Abstand so\n      klein wie möglich einstellen!\n";
 elif [ $metal == "ag" ]; then
@@ -137,84 +155,109 @@ elif [ $metal == "ir" ]; then
 fi
 printf "\n > 2) ${size} ml Borosilikatglas bis zum Rand mit\n      H²O füllen & auf Heizplatte stellen!\n";
 source "$libsPath/elektrodenPosition.sh" || exit 1; 
-printf " > Taste drücken um fortzufahren oder beenden mit ctrl+c!";
-read -n 1 -s -r -p "";
+# direkt Anfangen ohne Bestätigung vom User
+if [ "$directstart" = "false" ]; then
+    printf " > Taste  = weiter\n   ctrl+c = beenden"
+    waitKey
+fi
 printf "\n\n";
 clear;
-230V $heizplatteRelais 1 1;
-sleep 1;
-# Ist genügend Energie vorhanden? Andernfalls beenden
+printf "\n";
+showLogo
+echo -e "";
+echo -e " .------------------------------------------------.";
+echo -e " | E\\tml\\tPPM\\tKochen\\t\\t Plasma\\t  |";
+echo -e " |------------------------------------------------.";
+echo -e " | ${metal}\\t${size} ml\\t${ppm} PPM\\t$(date -d@$(($_endPlatte)) -u +%H:%M:%S)\\t $(date -d@$(( $time)) -u +%H:%M:%S) |";
+echo -e " *------------------------------------------------*";
+rounds=$(($time/$maxRuntime))
+[ $(($time % $maxRuntime)) -gt 0 ] && rounds=$(($rounds + 1))
+[ $rounds -lt 1 ] && rounds=1
+echo -e " | > Gesamtdauer: ~ $(date -d@$(($_endPlatte+$time+300)) -u +%H:%M:%S)"
+230V $heizplatteRelais 1 >/dev/null 2>&1
+sleep 0.5
 status=$(230V $heizplatteRelais)
-if [[ "$status" -eq 0 ]]; then
-    230V $trafoRelais 0 1;
-    exit 1;
+if [ "$status" -eq 0 ]; then
+    printf " |\e[1;31m > Es ist zu wenig\e[0m\n"
+    printf " |\e[1;31m > Leistung vorhanden! Abbruch.\e[0m\n"
+    exit 1
 fi
-
+echo -e " | > Aufheizen"
 for number in $(seq 0 ${_endPlatte}) # Progress Bar anzeigen
 do
-    sleep 1;
-    ProgressBar ${number} ${_endPlatte} "$(date -d@$_endPlatte -u +%H:%M:%S) Aufheizen";
+    sleep 1
+    ProgressBarHeat ${number} ${_endPlatte} "$(date -d@$_endPlatte -u +%H:%M:%S)"
 done
-230V $heizplatteRelais 0 1;
-rounds=$(($time/$maxRuntime));
-[ $(($time % $maxRuntime)) -gt 0 ] && rounds=$(($rounds + 1));
-[ $rounds -lt 1 ] && rounds=1;
-echo -e "\n > Produktionsdauer: ~$(($time/60)) min";
-if [ $rounds -gt 1 ]; then
-    echo -e " > Nachjustieren jede: $(($maxRuntime/60)) min";
-fi
+echo -e "\n | > Rundendauer: $(date -d@$(($maxRuntime)) -u +%H:%M:%S)"
+echo -e " | > Anzahl Runden: $rounds"
+
 for (( r=1; r<=$rounds; r++ ))
 do 
-    printf "\e[1;31m > TRAFO WIRD GLEICH EINGESCHALTET !!!ACHTUNG LEBENSGEFAHR!!! \e[0m \n";
-    $soundPath/enableTrafo;
-    230V $trafoRelais 1 1;
-    sleep 1;
-
+    230V $heizplatteRelais 0 >/dev/null 2>&1
+    printf " | \e[1;31m> TRAFO WIRD GLEICH EINGESCHALTET!!!\e[0m \n"
+    printf " | \e[1;31m> ACHTUNG LEBENSGEFAHR!!!\e[0m\n"
+    $soundPath/enableTrafo >/dev/null 2>&1
+    230V $trafoRelais 1 >/dev/null 2>&1
+    sleep 0.4
     status=$(230V $trafoRelais)
-    if [[ "$status" -eq 0 ]]; then
-        230V $heizplatteRelais 0 1;
-        exit 1;
+    if [ "$status" -eq 0 ]; then
+        printf " |\e[1;31m > Es ist zu wenig\e[0m"
+        printf " |\e[1;31m > Leistung vorhanden! Abbruch.\e[0m"
+        exit 1
     fi
-    
-    
-    # TODO rundenkochzeit am anfang setzen für jede größe
-    [ $size -eq 200 ] && 230V $heizplatteRelais 1 1; # Wenn Menge >= 200 dann Heizplatte aktivieren
-    [ $size -eq 200 ] && 230V $heizplatteRelais 0 120 & disown; # Wenn Menge >= 200 dann Heizplatte nach x sekunden wieder ausschalten
-    
-    
-    sleep 1;
-
-    
-    if [ $size -lt 1000 ]; then # Kleine Mengen mit vielen Runden
-        if [ $(($r % 2)) == 0 ]; then  # jede zweite Runde Köcheln für 4 Minuten
-            230V $heizplatteRelais 1 1;
-            sleep 1;
-            status=$(230V $heizplatteRelais)
-            if [[ "$status" -eq 0 ]]; then
-                230V $trafoRelais 0 1;
-                exit 1;
-            fi
-            230V $heizplatteRelais 0 240 & disown;
+    # jede zweite Runde Heizplatte hinzuschalten
+    if [ $(($r % 2)) == 0 ]; then
+        printf "\e[0m |\e[1;33m > HEIZPLATTE WIRD\e[0m\n"
+        printf "\e[0m |\e[1;33m > UNTERSTÜTZEND HINZUGESCHALTET!\e[0m\n"
+        230V $heizplatteRelais 1 >/dev/null 2>&1
+        sleep 0.4
+        status=$(230V $heizplatteRelais)
+        if [ "$status" -eq 0 ]; then
+            printf " |\e[1;31m > Es ist zu wenigAbbruch.\e[0m\n"
+            printf " |\e[1;31m > Leistung vorhanden! Abbruch.\e[0m\n"
+            exit 1
         fi
+        case $size in
+            100)
+                230V $heizplatteRelais 0 120 &
+                bgPids+=($!)
+            ;;
+            200)
+                230V $heizplatteRelais 0 240 &
+                bgPids+=($!)
+            ;;
+            400)
+                230V $heizplatteRelais 0 500 &
+                bgPids+=($!)
+            ;;
+            1000)
+                230V $heizplatteRelais 0 1000 &
+                bgPids+=($!)
+            ;;
+            2000)
+                230V $heizplatteRelais 0 1800 &
+                bgPids+=($!)
+            ;;
+        esac
     fi
-    [ $time -lt $maxRuntime ] && _endt=$time || _endt=$maxRuntime;
-    
-    
+    [ $time -lt $maxRuntime ] && _endt=$time || _endt=$maxRuntime
     for numbera in $(seq 0 ${_endt})
     do
         sleep 1;
-        ProgressBar ${numbera} ${_endt} "Runde $r/$rounds";
+        ProgressBarRound ${numbera} ${_endt} "Runde $r/$rounds"
     done
-    230V $trafoRelais 0 1;
-    230V $heizplatteRelais 0 1;
-    time=$(($time - $_endt));
+    230V $trafoRelais 0 >/dev/null 2>&1
+    230V $heizplatteRelais 0 >/dev/null 2>&1
+    time=$(($time - $_endt))
     if [ "$rounds" == "$r" ]; then
-        printf "\n\e[1;33m > Produktion fertig! \e[0m \n\n";
-        $soundPath/finishedTrafo & disown;
-        exit 0;
+        printf "\n\e[0m |\e[1;33m > Produktion fertig! \e[0m"
+        $soundPath/finishedTrafo >/dev/null 2>&1
+        exit 0
     else
-        $soundPath/disableTrafo & disown;
-        printf "\n\e[1;31m > Elektroden neu positionieren und Taste drücken um fortzufahren oder beenden mit ctrl+c! \e[0m\n";
-        read -n 1 -s -r -p "";
+        $soundPath/disableTrafo >/dev/null 2>&1
+        printf "\n\e[0m |\e[1;33m > Elektroden prüfen"
+        printf "\n\e[0m |\e[1;33m > Weiter  = ENTER,"
+        printf "\n\e[0m |\e[1;33m > beenden = STRG+C\e[0m"
+        waitEnter
     fi
 done
